name: recepies
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: "^1.0.0"
  flutter_mobx:

  flutter_hooks:
  
  moor_flutter: ^3.1.0
  
  get_it:
  
  flutter_form_builder: ^3.9.0

  rxdart: ^0.24.0  
  
  optional:
  equatable:

  freezed: ^0.11.0
    
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^1.10.1
  
  moor_generator: ^3.3.1
  mobx_codegen:

flutter:
  uses-material-design: true

