name: recepies
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: "^1.0.0"
  flutter_mobx:

  flutter_hooks:
  
  moor_flutter:
  
  get_it:
  
  flutter_form_builder: ^3.9.0

  rxdart: ^0.24.0  
  
  optional:
  equatable:

  freezed: ^0.10.6
    
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner:
  
  moor_generator:
  mobx_codegen:

flutter:
  uses-material-design: true

